baseURL = "https://ch-yang1273.github.io/"
title = "ych`s blog" # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
theme = "hugo-clarity"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."

# canonifyurls = true
paginate = 10

disqusShortname = ""

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
